### ISSUE TITLE
WebDAV Authentication 

### ISSUE THREAD

**Issue by emresaracoglu** [krueschan/phpZoteroWebDAV#5]
Hi,
I think need a username/password for webDAV. How I can make this script with authentication?

**Comment by krueschan** [comment]
I think this is covered (or at least mentioned) in the installation instructions, but in case you missed it: for authentication, you just use your web server's (e.g. apache) basic authentication. This is done typically using .htaccess and .htpasswd files - google htaccess htpasswd to find instructions.

**Comment by emresaracoglu** [comment]
I see thank you @krueschan
