### ISSUE TITLE
"err is underfined" in zotero

### ISSUE THREAD

**Issue by cjvanlissa** [krueschan/phpZoteroWebDAV#7]
When I sync to Zotero's servers, there is no problem, but when I try to sync to webdav on my personal domain, my Zotero client refuses to sync and gives the error: "err is underfined".

The webdav interface on my domain does show the list of my publications, but the attachments are not synced.

**Comment by krueschan** [comment]
Hi CJ,
I’m actually not maintaining this project anymore. On the GitHub project page I’m pointing to a fork where continued maintenance used to happen so I suggest checking out that code (perhaps it already solved your problem) and contacting the folks over there.
Krueschan.

---
Christian Holz
Skype: cbholz | +1-613-618-4601 (UTC-5h)
________________________________

**Comment by cjvanlissa** [comment]
Gotcha, and I appreciate it. I didn't look closely enough! Best, Caspar
